on:
  push:
  pull_request:
    branches:
      - main
name: build_deploy

jobs:
  build_deploy:
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-r@v2
      
#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y pandoc libcurl4-openssl-dev libssl-dev
      
      - name: Install TinyTeX
        run: |
          install.packages(c('tinytex', 'plotly'))
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages(c('remotes', 'BiocManager', 'rmarkdown'))
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          install.packages('sessioninfo')
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Render book (bs4_book)
        run: |
          setwd("docs")
          bookdown::render_book('index.Rmd', 'bookdown::bs4_book')
        shell: Rscript {0}
      

      # deploy needs rsync? Seems so.
#      - name: Install deploy dependencies
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#        run: |
#         apt-get update && apt-get -y install rsync
          
      - name: Deploy 🚀
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_book
